### PR TITLE
Add NewInstance method to access instance config

### PR DESCRIPTION
**Pull request by op**
This adds a `NewInstance` method which allow you to use the connection for other uses instead of a `sql.DB` instance.

### CODE REVIEW

**Comment by peterldowns** [comment]
Hi, thanks for the contribution! Can you explain some more of the reasoning behind why you want this? I'm pretty sure this is a good idea, but I want to better understand why you want it.

**Comment by op** [comment]
> Hi, thanks for the contribution! Can you explain some more of the reasoning behind why you want this? I'm pretty sure this is a good idea, but I want to better understand why you want it.

Thank you for the project! :dancers: 

The reason is because I'd like to be able to write helper functions to eg. call `pgxpool.New()` etc, or something that implements a different interface than the `sql.DB` -- eg `pgutil.DB`.

Do you think this is conflicting with your ideas for the project? I'm not very fond of the name `NewInstance` but I tried to follow the structure. And `NewConfig` doesn't fit at all.

I guess you're able to somehow get a hold of the raw connection and convert it, but that feels dirty. An alternative solution would be to create a `StealConfigurationMigrator` to make a copy of the instance configuration.

Feel free to improve this any way you want! :)

**Comment by peterldowns** [comment]
That's a great explanation, and it looks like @rshep3087 also would benefit (see https://github.com/peterldowns/pgtestdb/issues/4). I'll add this but I'm going to use a slightly different name. Again, I'll happily give you credit in the commit message, and thank you for the great suggestion.

**Comment by peterldowns** [comment]
This should be resolved as of [11a64cc](https://github.com/peterldowns/pgtestdb/commit/11a64ccdbb8b75985619d545401dfec44fdc2c34). Thank you again for the good suggestion, and please let me know if the new method is insufficient in any way.

**Pull request closed without merging**
